language: python

python:
- 2.7
- 3.2
- 3.3
- 3.4
- pypy

env:
- DJANGO_VERSION=1.7.8
- DJANGO_VERSION=1.8.2

install:
- pip install -q -r requirements.txt
- pip install -q coveralls
- pip install -q Django==$DJANGO_VERSION

script: coverage run --source=quotes manage.py test

after_success:
    coveralls
