language: python

python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- pyp3
- nightly


env:
- DJANGO_VERSION=1.7.10
- DJANGO_VERSION=1.8.4

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: nightly

install:
- pip install -q -r requirements.txt
- pip install -q coveralls codecov
- pip install -q Django==$DJANGO_VERSION

script: coverage run --source=quotes manage.py test

after_success:
- coveralls
- codecov
