language: python

python:
- 3.5
- 3.6
- 3.7
- pypy3

env:
- DJANGO_VERSION=1.11.8
- DJANGO_VERSION=2.0.1
- DJANGO_VERSION=LATEST

matrix:
  allow_failures:
    - python: pypy3
    - env: DJANGO_VERSION=LATEST

install:
- pip install -q -r requirements.txt
- pip install -q coveralls codecov
- if [[ $DJANGO_VERSION != "LATEST" ]]; then pip install -q Django==$DJANGO_VERSION; fi
- if [[ $DJANGO_VERSION == "LATEST" ]]; then pip install -U Django; fi

script: coverage run --source=quotes manage.py test

after_success:
- coveralls
- codecov
